### ISSUE TITLE
Could not create stylelint process.

### ISSUE THREAD

**Issue by red2678** [Jardinero/stylelint-plugin#9]
Hi, I am getting this issue in Webstorm 2016.3.3

> Could not create stylelint process.: Cannot run program "\stylelint.cmd" (in directory "D:\xxx\xxx\xxx"): 
> CreateProcess error=2, The system cannot find the file specified

I have style lint installed via NPM. Any ideas?

Thanks!!

**Comment by niutech** [comment]
First check if you have installed stylelint globally (npm install -g).
Find the stylelint.cmd file path, it should be
%AppData%\npm\node_modules\stylelint, finally paste it into Settings.

**Comment by red2678** [comment]
So I cannot use this plugin with the locally installed cmd in my project's node_modules folder?

**Comment by tilwinjoy** [comment]
I have the same problem. Can't this plugin have stylelint as a local dependency?

> First check if you have installed stylelint globally (npm install -g).
Find the stylelint.cmd file path, it should be
%AppData%\npm\node_modules\stylelint, finally paste it into Settings.

What settings?

**Comment by felu** [comment]
Same issue here.

I installed stylelint with 'npm install -g stylelint' in Windows PowerShell. It installed stylelint to 'C:\Program Files\nodejs\node_modules\stylelint' (not to %AppData%). If I set this path in IntelliJ, it gives me the same error as mentioned above.

There is no stylelint.cmd file in that directory. Instead I find it ( 'where.exe stylelint.cmd' ) 'C:\Program Files\nodejs\stylelint.cmd'. If I set this path, I get an error in IntelliJ 'Stylelint: please specify Stylelint package correctly: ".../package.json" file not found' ( package.json of course is installed in C:\Program Files\nodejs\node_modules\stylelint )

I also would prefer to run stylelint against locally dependencies.
